alias       l='ls -laG'
alias      ..='cd ..'
alias      mm='mate .'
alias    cpwd="pwd | pbcopy"
alias    ppwd="cd `pbpaste`"
alias    hcal='cal | grep -C6 --color -e " $(date +%e)" -e "^(date +%e)"'
alias      ss='script/server'
alias     sss='script/server -estaging'
alias      sc='script/console'
alias     scs='script/console staging'
alias     ssd='script/server -d'
alias     ssk='kill `cat tmp/pids/server.pid`'
alias     ssr='ssk && ssd'
alias    sedi="sed -i '' -e "
alias  grepps="ps aux | grep"
alias gitconf="mate .git/config"
alias  gitmod="mate .gitmodules"
alias      tf="tail -f "
alias   mysql='mysql5'
alias tiny_ci="open -a 'Google Chrome' http://192.168.82.134:7199/"
alias      vi='vi -p'
alias   nrake='NONET=true rake'
alias    rmrf='rm -rf'
alias     bll='vi $HOME/.bash_login_local'
alias    whid='mate $HOME/what_have_i_done.txt'
alias      ip='ifconfig | grep "broadcast" | cut -b7-20'
alias       z='mate $HOME/.zsh'
alias      zr='source $HOME/.zshrc'
alias      dh='dirs -v'
alias      guardian= lynx http://ww.guardian.co.uk
